logging:
  level:
    io:
      spring:
        cloud:
          samples: INFO

foo: baz

fortune:
  fallbackFortune: The fog should lift today.

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
