logging:
  level:
    io:
      spring:
        cloud:
          samples: DEBUG

foo: bardog

fortune:
  fallbackFortune: The fog should lift today.

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
